name: eid sigin

on:
  push:
    branches:
      - main

jobs:
  ssh-connect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo node11.puyuma.org >> ~/.ssh/known_hosts

      - name: SSH to node11.puyuma.org
        run: |
          ssh -v -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@node11.puyuma.org -p 2222 "ansible-playbook ansible-playbook/eid-signin.yaml"
